/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "unit_tests/_unittests.check" instead.
 */

#include <check.h>

#include <check.h>

#include "../quadratic_equation.h"

#define CK_FORK 0


START_TEST(test_errors_1)
{
double a = NAN;
double b = 124.12424;
double c = -4.54;
quadratic_roots roots;
roots = solve_equation(a, b, c);
ck_assert_int_eq(INVALID_ARGUMENTS, roots.err);

}
END_TEST

START_TEST(test_errors_2)
{
double a = 5387873.587;
double b = 124.12424;
double c = -NAN;
quadratic_roots roots;
roots = solve_equation(a, b, c);
ck_assert_int_eq(INVALID_ARGUMENTS, roots.err);

}
END_TEST

START_TEST(test_errors_3)
{
double a = 835293.958;
double b = INFINITY;
double c = -4.54;
quadratic_roots roots;
roots = solve_equation(a, b, c);
ck_assert_int_eq(INVALID_ARGUMENTS, roots.err);

}
END_TEST

START_TEST(test_errors_4)
{
double a = 835293.958;
double b = 15346.245;
double c = -INFINITY;
quadratic_roots roots;
roots = solve_equation(a, b, c);
ck_assert_int_eq(INVALID_ARGUMENTS, roots.err);

}
END_TEST

START_TEST(test_errors_5)
{
double a = 0.0;
double b = 0.0;
double c = 0.0;
quadratic_roots roots;
roots = solve_equation(a, b, c);
ck_assert_int_eq(1, (roots.err == ERROR_INFINITE_NUMBER_OF_ROOTS) || (roots.err == WARNING_INFINITE_NUMBER_OF_ROOTS));
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("test_errors_");
    TCase *tc1_1 = tcase_create("test_errors_");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, test_errors_1);
    tcase_add_test(tc1_1, test_errors_2);
    tcase_add_test(tc1_1, test_errors_3);
    tcase_add_test(tc1_1, test_errors_4);
    tcase_add_test(tc1_1, test_errors_5);

    srunner_set_fork_status(sr, CK_NOFORK);

 srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
